// Placeholder data used when Sanity is not configured (project ID = PLACEHOLDER)
// This lets the site build and render without a Sanity backend.

export const placeholderPoems = [
  {
    _id: "poem-1",
    title: "After Rain",
    slug: { current: "after-rain" },
    excerpt: "The garden holds its breath, each leaf a cupped hand catching what the sky could not keep.",
    date: "2026-03-20",
    tags: ["Nature"],
    featured: true,
    body: [
      {
        _type: "block",
        children: [
          { _type: "span", text: "The garden holds its breath," },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "each leaf a cupped hand" },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "catching what the sky" },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "could not keep." },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [{ _type: "span", text: "" }],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "I press my palm" },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "to the wet bark" },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "and feel the pulse" },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "of something " },
          { _type: "span", text: "older", marks: ["em"] },
        ],
        style: "normal",
      },
      {
        _type: "block",
        children: [
          { _type: "span", text: "than my asking." },
        ],
        style: "normal",
      },
    ],
  },
  {
    _id: "poem-2",
    title: "The Architecture of Rain",
    slug: { current: "the-architecture-of-rain" },
    excerpt: "We build houses of glass to watch the sky break...",
    date: "2026-03-15",
    tags: ["Free Verse", "Nature"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "We build houses of glass" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "to watch the sky break," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "forgetting that water has no memory" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "but the earth remembers everything." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "The soil drinks the storm" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "and turns it into veins of green," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "a silent rebellion against the gray" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "that hangs above us." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I stood in the doorway" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "as the world washed its hands," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "wondering if the rivers" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "ever get tired of moving forward." }], style: "normal" },
    ],
  },
  {
    _id: "poem-3",
    title: "Winter's Edge",
    slug: { current: "winters-edge" },
    excerpt: "Frost upon the branch...",
    date: "2026-02-28",
    tags: ["Haiku", "Winter"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "Frost upon the branch," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "The breath of the quiet dawn," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "Shadows turn to glass." }], style: "normal" },
    ],
  },
  {
    _id: "poem-4",
    title: "The Quiet Tide",
    slug: { current: "the-quiet-tide" },
    excerpt: "The ocean speaks in syllables of foam...",
    date: "2026-02-20",
    tags: ["Sonnet", "Ocean"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "The ocean speaks in syllables of foam," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "A language written deep within the crest." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "It drags the wandering sailors back to home," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "And pulls the weary sun into the west." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "We stand upon the borders of the sand," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "And watch the monumental waters shift." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "It is a force we cannot understand," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "A violent beauty, or a sudden gift." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "For all the rigid structures that we make," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "The tides will always rise to claim their due." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "There is a promise that it will not break," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "To wash the stones and start the world anew." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "So let the currents carry what they will," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "And leave the empty shores profoundly still." }], style: "normal" },
    ],
  },
  {
    _id: "poem-5",
    title: "The Weight of Mornings",
    slug: { current: "the-weight-of-mornings" },
    excerpt: "Before coffee, before news, when the house is still a shell of sleeping breath.",
    date: "2026-02-10",
    tags: ["Reflection", "Memory"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "Before coffee, before news," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "when the house is still" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "a shell of sleeping breath—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I sit with the weight" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "of another day arriving" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "uninvited, certain," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "full of its own purposes." }], style: "normal" },
    ],
  },
  {
    _id: "poem-6",
    title: "Root System",
    slug: { current: "root-system" },
    excerpt: "Underground, the conversation continues — fungi passing notes between the oaks.",
    date: "2026-01-25",
    tags: ["Nature"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "Underground, the conversation continues—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "fungi passing notes between the oaks," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "a network older than language," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "older than the need to be understood." }], style: "normal" },
    ],
  },
  {
    _id: "poem-7",
    title: "Dusk Pastoral",
    slug: { current: "dusk-pastoral" },
    excerpt: "The field gives back its heat in slow waves, and the last swallows stitch the sky shut.",
    date: "2026-01-15",
    tags: ["Nature", "Free Verse"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "The field gives back its heat" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "in slow waves, and the last swallows" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "stitch the sky shut." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I have watched this closing" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "a thousand times and still" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "it catches me mid-step," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "mid-thought, mid-life." }], style: "normal" },
    ],
  },
  {
    _id: "poem-8",
    title: "Moss Hymn",
    slug: { current: "moss-hymn" },
    excerpt: "Old stone, soft cloak — patience makes its argument in green.",
    date: "2026-01-08",
    tags: ["Haiku", "Nature"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "Old stone, soft cloak worn—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "patience makes its argument" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "in tender greens." }], style: "normal" },
    ],
  },
  {
    _id: "poem-9",
    title: "Letter to My Hands",
    slug: { current: "letter-to-my-hands" },
    excerpt: "You who have held everything and kept nothing — I owe you an apology.",
    date: "2025-12-20",
    tags: ["Reflection", "Free Verse"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "You who have held everything" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "and kept nothing—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I owe you an apology." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "Every door you opened" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I walked through without looking back." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "Every page you turned" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I read with someone else's eyes." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "But you kept working—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "kneading bread, pulling weeds," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "writing these lines" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "that try to say what you already know." }], style: "normal" },
    ],
  },
  {
    _id: "poem-10",
    title: "Equinox",
    slug: { current: "equinox" },
    excerpt: "The day and the dark agree, briefly, to share the table.",
    date: "2025-12-05",
    tags: ["Sonnet", "Nature"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "The day and the dark agree, briefly," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "to share the table, split the bread," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "and for one turning of the earth" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "neither claims the larger share." }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "I want to live inside this balance—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "the trembling midpoint, the held breath" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "before the scales tip toward winter" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "or the long exhale of spring." }], style: "normal" },
    ],
  },
  {
    _id: "poem-11",
    title: "Kitchen Window",
    slug: { current: "kitchen-window" },
    excerpt: "Steam from the kettle fogs the glass — through it, the yard becomes a watercolor.",
    date: "2025-11-18",
    tags: ["Memory", "Reflection"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "Steam from the kettle" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "fogs the glass—through it," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "the yard becomes a watercolor:" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "green bleeds into brown" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "bleeds into the memory" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "of my mother's kitchen," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "same window, same fog," }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "different hands on the cup." }], style: "normal" },
    ],
  },
  {
    _id: "poem-12",
    title: "Crow Song",
    slug: { current: "crow-song" },
    excerpt: "Three caws at dawn — a language I almost understand, like a word on the tip of forgetting.",
    date: "2025-11-02",
    tags: ["Haiku", "Nature"],
    featured: false,
    body: [
      { _type: "block", children: [{ _type: "span", text: "Three caws at cold dawn—" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "a word on the tip of all" }], style: "normal" },
      { _type: "block", children: [{ _type: "span", text: "this world's forgetting." }], style: "normal" },
    ],
  },
];

export const placeholderBlogPosts = [
  {
    _id: "blog-1",
    title: "On Keeping a Notebook",
    slug: { current: "on-keeping-a-notebook" },
    excerpt:
      "There is something about the physical act of writing — pen to paper, not key to screen — that unlocks a different kind of thinking.",
    date: "2026-03-08",
    tags: ["Writing"],
    coverImage: null,
  },
  {
    _id: "blog-2",
    title: "Why I Stopped Submitting",
    slug: { current: "why-i-stopped-submitting" },
    excerpt:
      "The literary magazine circuit is a strange game. You write something intimate, format it in 12pt Times New Roman, and send it to strangers.",
    date: "2026-02-20",
    tags: ["Publishing"],
    coverImage: null,
  },
  {
    _id: "blog-3",
    title: "Morning Observations",
    slug: { current: "morning-observations" },
    excerpt:
      "On the ritual of walking before the world wakes, and what the garden teaches about patience when you stop trying to make things grow.",
    date: "2026-03-12",
    tags: ["Nature", "Reflection"],
    coverImage: null,
  },
];

export const placeholderEvents = [
  {
    _id: "event-1",
    title: "Spring Reading Series",
    description: "An evening of new work from Ink & Earth alongside three guest poets. Wine, conversation, and the first poems of the season. Doors open at 6:30 PM.",
    date: "2026-04-15T19:00:00Z",
    location: "The Bindery, Portland, OR",
    link: null,
    time: "7:00 PM",
    admission: "Free",
  },
  {
    _id: "event-2",
    title: "Open Mic Night",
    description: "Bring your voice, bring your verse. Five-minute slots, all forms welcome. Sign-up at the door. Coffee and pastries provided by the cafe.",
    date: "2026-05-01T20:00:00Z",
    location: "Ink & Bean Cafe, Seattle, WA",
    link: null,
    time: "8:00 PM",
    admission: "Free",
  },
  {
    _id: "event-3",
    title: "Chapbook Launch: The Understory",
    description: "A reading and signing for the new chapbook. Limited letterpress editions available at the event. Followed by a Q&A on writing from the natural world.",
    date: "2026-06-10T18:30:00Z",
    location: "Powell's City of Books, Portland, OR",
    link: null,
    time: "6:30 PM",
    admission: "Free · Books available for purchase",
  },
  {
    _id: "event-4",
    title: "Writing Workshop: Rooted Verse",
    description: "A half-day workshop on writing poetry grounded in place and landscape. We'll walk the garden, observe, and draft new work. Bring a notebook and comfortable shoes. Limited to 12 participants.",
    date: "2026-07-20T10:00:00Z",
    location: "Leach Botanical Garden, Portland, OR",
    link: null,
    time: "10:00 AM – 1:00 PM",
    admission: "$35 · Limited spots",
  },
  {
    _id: "event-5",
    title: "Summer Solstice Reading",
    description: "Poetry under the longest light. An outdoor reading at golden hour, followed by a communal meal. Bring a blanket and a poem to share.",
    date: "2025-06-21T19:00:00Z",
    location: "Oaks Bottom Wildlife Refuge, Portland, OR",
    link: null,
    time: "7:00 PM",
    admission: "Free",
  },
  {
    _id: "event-6",
    title: "Poetry & Fermentation",
    description: "An unlikely pairing: readings between courses of fermented foods. What does patience taste like? What does time do to language? An evening of slow things.",
    date: "2025-09-14T18:00:00Z",
    location: "Fermenter's Kitchen, Ashland, OR",
    link: null,
    time: "6:00 PM",
    admission: "$20 · Includes tasting",
  },
  {
    _id: "event-7",
    title: "Fall Reading: Ember Hymnal",
    description: "Poems from the collection written in the wake of wildfire season. A conversation about grief, landscape, and what grows back.",
    date: "2025-10-28T19:00:00Z",
    location: "Literary Arts, Portland, OR",
    link: null,
    time: "7:00 PM",
    admission: "Free",
  },
];

export const placeholderPublications = [
  {
    _id: "pub-1",
    title: "Small Hours",
    description: null,
    coverImage: null,
    year: 2025,
    buyLink: null,
  },
  {
    _id: "pub-2",
    title: "Field Notes from Nowhere",
    description: null,
    coverImage: null,
    year: 2023,
    buyLink: null,
  },
];

export const placeholderAbout = {
  subtitle: "Poet, observer, occasional gardener",
  photo: null,
  bio: [
    {
      _type: "block",
      children: [
        {
          _type: "span",
          text: "I write about the small things — the ones that happen while you're busy with the big ones. The crack in the sidewalk where the dandelion insists. The conversation you replay at 2am. The particular blue of a Tuesday sky in March.",
        },
      ],
      style: "normal",
    },
    {
      _type: "block",
      children: [
        {
          _type: "span",
          text: "I've been writing poetry for twenty years, publishing for ten, and questioning whether any of it matters for all of it. The answer, I've decided, is that mattering isn't the point. The writing is the point.",
        },
      ],
      style: "normal",
    },
  ],
};

export const placeholderSettings = {
  siteName: "Ink & Earth",
  tagline: "Poetry rooted in the soil of being",
  socialLinks: [
    { platform: "Instagram", url: "#" },
    { platform: "Substack", url: "#" },
    { platform: "Bookshop", url: "#" },
  ],
  footerText: null,
};
